### ISSUE TITLE
Missing file: w5x00_gpiO_irq.h

### ISSUE THREAD

**Issue by jondurrant** [Wiznet/RP2040-HAT-FREERTOS-C#1]
RP2040-HAT-FREERTOS-C/port/ioLibrary_Driver/src/w5x00_gpio_irq.c:19:10: fatal error: w5x00_gpiO_irq.h: No such file or directory
   19 | #include "w5x00_gpiO_irq.h"

**Comment by Giung951** [comment]
Hello @jondurrant

> RP2040-HAT-FREERTOS-C/port/ioLibrary_Driver/src/w5x00_gpio_irq.c:19:10: fatal error: w5x00_gpiO_irq.h: No such file or directory 19 | #include "w5x00_gpiO_irq.h"

Fixed this issue.

Clone the fixed example and try building again.
